# Generated by Django 4.2 on 2023-04-21 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=250, verbose_name='Last Name')),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='User Profile Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='followers')),
                ('following', models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='following')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
